//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectatorFootball.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Draft
    {
        public long ID { get; set; }
        public long Season_ID { get; set; }
        public long Round { get; set; }
        public long Franchise_ID { get; set; }
        public long Player_ID { get; set; }
    
        public virtual Franchise Franchise { get; set; }
        public virtual Player Player { get; set; }
    }
}
