//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectatorFootball.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Player_Kickoff_Defenders
    {
        public long Game_ID { get; set; }
        public long Player_ID { get; set; }
        public long Franchise_ID { get; set; }
        public long Forced_Fumbles_Kickoffs { get; set; }
        public long Fumbles_Kickoffs_Recovered { get; set; }
        public long Fumbles_Kickoffs_Recovered_TDs { get; set; }
        public long Fumbles_Kickoffs_Recovered_Yards { get; set; }
        public long Kickoff_Tackles { get; set; }
        public long KickOff_Onside_Kick_Recoveries { get; set; }
    
        public virtual Franchise Franchise { get; set; }
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
