//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectatorFootball.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Player_Pass_Rushers_Stats
    {
        public long Game_ID { get; set; }
        public long Player_ID { get; set; }
        public long Def_Sacks { get; set; }
        public long Def_Rushing_Loss { get; set; }
        public long Def_Tackles { get; set; }
        public long Def_Missed_Tackles { get; set; }
        public long Def_Safety { get; set; }
        public long Def_TDs { get; set; }
        public long Forced_Fumbles { get; set; }
        public long Recovered_Fumbles { get; set; }
        public long Fumbles_Return_Yards { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
