//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectatorFootball.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Player_Offensive_Linemen_Stats
    {
        public long Game_ID { get; set; }
        public long Player_ID { get; set; }
        public long Franchise_ID { get; set; }
        public long Started { get; set; }
        public long Oline_Plays { get; set; }
        public long OLine_Sacks_Allowed { get; set; }
        public long OLine_Rushing_Loss_Allowed { get; set; }
        public long OLine_Missed_Block { get; set; }
        public long OLine_Pancakes { get; set; }
        public long QB_Pressures_Allowed { get; set; }
    
        public virtual Franchise Franchise { get; set; }
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
