//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectatorFootball.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Player_Kick_Returner_Stats
    {
        public long Game_ID { get; set; }
        public long Player_ID { get; set; }
        public long Franchise_ID { get; set; }
        public long Kickoffs_Returned { get; set; }
        public long Kickoffs_Returned_Yards { get; set; }
        public long Kickoffs_Returned_TDs { get; set; }
        public long Kickoff_Return_Yards_Long { get; set; }
        public long Kickoffs_Returned_Fumbles { get; set; }
        public long Kickoffs_Returned_Fumbles_Lost { get; set; }
    
        public virtual Franchise Franchise { get; set; }
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
