//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectatorFootball.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Player_Pass_Defense_Stats
    {
        public long Game_ID { get; set; }
        public long Player_ID { get; set; }
        public long Ints { get; set; }
        public long Def_Int_Yards { get; set; }
        public long Def_Safety { get; set; }
        public long Def_int_TDs { get; set; }
        public long Def_Pass_Defenses { get; set; }
        public long Tackles { get; set; }
        public long Def_Missed_Tackles { get; set; }
        public long Touchdowns_Surrendered { get; set; }
        public long Sacks { get; set; }
        public long Forced_Fumbles { get; set; }
        public long Fumble_Recoveries { get; set; }
        public long Fumble_Return_Yards { get; set; }
        public long Fumble_Return_TD { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
