//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectatorFootball.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Player_Passing_Stats
    {
        public long Game_ID { get; set; }
        public long Player_ID { get; set; }
        public long Franchise_ID { get; set; }
        public long Started { get; set; }
        public long Fumbles { get; set; }
        public long Fumbles_Lost { get; set; }
        public long Sacked { get; set; }
        public long Pass_Comp { get; set; }
        public long Pass_Att { get; set; }
        public long Pass_Yards { get; set; }
        public long Pass_TDs { get; set; }
        public long Pass_Ints { get; set; }
        public long Long { get; set; }
        public long Passes_Blocks { get; set; }
    
        public virtual Franchise Franchise { get; set; }
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
