//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectatorFootball.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Player_Punter_Stats
    {
        public long Game_ID { get; set; }
        public long Player_ID { get; set; }
        public long Started { get; set; }
        public long Fumbles { get; set; }
        public long num_punts { get; set; }
        public long Punt_yards { get; set; }
        public long Punt_Killed_att { get; set; }
        public long Punt_killed_num { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
