//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectatorFootball.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class League_Structure_by_Season
    {
        public long ID { get; set; }
        public string Short_Name { get; set; }
        public string Long_Name { get; set; }
        public string League_Logo_Filepath { get; set; }
        public string League_Logo_File { get; set; }
        public long Season_ID { get; set; }
        public long Number_of_weeks { get; set; }
        public long Number_of_Games { get; set; }
        public string Championship_Game_Name { get; set; }
        public long Num_Teams { get; set; }
        public long Num_Playoff_Teams { get; set; }
        public long Number_of_Conferences { get; set; }
        public long Number_of_Divisions { get; set; }
        public string Draft_Type_Code { get; set; }
        public long Injuries { get; set; }
        public long Penalties { get; set; }
    
        public virtual Season Season { get; set; }
    }
}
