//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectatorFootball.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class leagueContext : DbContext
    {
        public leagueContext()
            : base("name=leagueContext")
        {
        }


        public leagueContext(string connString)
    : base(connString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Award> Awards { get; set; }
        public virtual DbSet<Conference> Conferences { get; set; }
        public virtual DbSet<DBVersion> DBVersions { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Game_Player_Kick_Returner_Stats> Game_Player_Kick_Returner_Stats { get; set; }
        public virtual DbSet<Game_Player_Kicker_Stats> Game_Player_Kicker_Stats { get; set; }
        public virtual DbSet<Game_Player_Offensive_Linemen_Stats> Game_Player_Offensive_Linemen_Stats { get; set; }
        public virtual DbSet<Game_Player_Pass_Defense_Stats> Game_Player_Pass_Defense_Stats { get; set; }
        public virtual DbSet<Game_Player_Pass_Rushers_Stats> Game_Player_Pass_Rushers_Stats { get; set; }
        public virtual DbSet<Game_Player_Passing_Stats> Game_Player_Passing_Stats { get; set; }
        public virtual DbSet<Game_Player_Punter_Stats> Game_Player_Punter_Stats { get; set; }
        public virtual DbSet<Game_Player_Receiving_Stats> Game_Player_Receiving_Stats { get; set; }
        public virtual DbSet<Game_Player_Rushing_Stats> Game_Player_Rushing_Stats { get; set; }
        public virtual DbSet<Game_Player_Special_Team_Receive_Stats> Game_Player_Special_Team_Receive_Stats { get; set; }
        public virtual DbSet<Game_Player_Special_Teams_Has_Ball_Stats> Game_Player_Special_Teams_Has_Ball_Stats { get; set; }
        public virtual DbSet<Game_Scoring_Summary> Game_Scoring_Summary { get; set; }
        public virtual DbSet<Hall_of_Fame> Hall_of_Fame { get; set; }
        public virtual DbSet<League> Leagues { get; set; }
        public virtual DbSet<Player_Awards> Player_Awards { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Playoff_Teams> Playoff_Teams { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
    }
}
