//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectatorFootball.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Penalty()
        {
            this.Game_Player_Penalties_Stats = new HashSet<Game_Player_Penalties_Stats>();
        }
    
        public long ID { get; set; }
        public string Penalty_Type { get; set; }
        public long Declinable { get; set; }
        public long Loss_of_Down { get; set; }
        public string Code { get; set; }
        public Nullable<long> Yards { get; set; }
        public long Auto_First_Down { get; set; }
        public long Ass_After_Play { get; set; }
        public string Specific_Play_Type { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_Player_Penalties_Stats> Game_Player_Penalties_Stats { get; set; }
    }
}
