//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectatorFootball.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.Drafts = new HashSet<Draft>();
            this.Free_Agency = new HashSet<Free_Agency>();
            this.Game_Player_FG_Defense_Stats = new HashSet<Game_Player_FG_Defense_Stats>();
            this.Game_Player_Kick_Returner_Stats = new HashSet<Game_Player_Kick_Returner_Stats>();
            this.Game_Player_Kicker_Stats = new HashSet<Game_Player_Kicker_Stats>();
            this.Game_Player_Kickoff_Defenders = new HashSet<Game_Player_Kickoff_Defenders>();
            this.Game_Player_Kickoff_Receiver_Stats = new HashSet<Game_Player_Kickoff_Receiver_Stats>();
            this.Game_Player_Offensive_Linemen_Stats = new HashSet<Game_Player_Offensive_Linemen_Stats>();
            this.Game_Player_Pass_Defense_Stats = new HashSet<Game_Player_Pass_Defense_Stats>();
            this.Game_Player_Pass_Rushers_Stats = new HashSet<Game_Player_Pass_Rushers_Stats>();
            this.Game_Player_Passing_Stats = new HashSet<Game_Player_Passing_Stats>();
            this.Game_Player_Penalties_Stats = new HashSet<Game_Player_Penalties_Stats>();
            this.Game_Player_Penalty_Stats = new HashSet<Game_Player_Penalty_Stats>();
            this.Game_Player_Punt_Defenders = new HashSet<Game_Player_Punt_Defenders>();
            this.Game_Player_Punt_Receiver_Stats = new HashSet<Game_Player_Punt_Receiver_Stats>();
            this.Game_Player_Punt_Returner_Stats = new HashSet<Game_Player_Punt_Returner_Stats>();
            this.Game_Player_Punter_Stats = new HashSet<Game_Player_Punter_Stats>();
            this.Game_Player_Receiving_Stats = new HashSet<Game_Player_Receiving_Stats>();
            this.Game_Player_Rushing_Stats = new HashSet<Game_Player_Rushing_Stats>();
            this.Hall_of_Fame = new HashSet<Hall_of_Fame>();
            this.Injuries = new HashSet<Injury>();
            this.Player_Awards = new HashSet<Player_Awards>();
            this.Player_Ratings = new HashSet<Player_Ratings>();
            this.Training_Camp_by_Season = new HashSet<Training_Camp_by_Season>();
        }
    
        public long ID { get; set; }
        public Nullable<long> Franchise_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public long Age { get; set; }
        public long Height { get; set; }
        public long Weight { get; set; }
        public string Handedness { get; set; }
        public string HomeTown { get; set; }
        public long Pos { get; set; }
        public Nullable<long> Jersey_Number { get; set; }
        public long Retired { get; set; }
        public long Eligible_for_Draft { get; set; }
        public string Draft_Profile { get; set; }
        public double Draft_Grade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Draft> Drafts { get; set; }
        public virtual Franchise Franchise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Free_Agency> Free_Agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_Player_FG_Defense_Stats> Game_Player_FG_Defense_Stats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_Player_Kick_Returner_Stats> Game_Player_Kick_Returner_Stats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_Player_Kicker_Stats> Game_Player_Kicker_Stats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_Player_Kickoff_Defenders> Game_Player_Kickoff_Defenders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_Player_Kickoff_Receiver_Stats> Game_Player_Kickoff_Receiver_Stats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_Player_Offensive_Linemen_Stats> Game_Player_Offensive_Linemen_Stats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_Player_Pass_Defense_Stats> Game_Player_Pass_Defense_Stats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_Player_Pass_Rushers_Stats> Game_Player_Pass_Rushers_Stats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_Player_Passing_Stats> Game_Player_Passing_Stats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_Player_Penalties_Stats> Game_Player_Penalties_Stats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_Player_Penalty_Stats> Game_Player_Penalty_Stats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_Player_Punt_Defenders> Game_Player_Punt_Defenders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_Player_Punt_Receiver_Stats> Game_Player_Punt_Receiver_Stats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_Player_Punt_Returner_Stats> Game_Player_Punt_Returner_Stats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_Player_Punter_Stats> Game_Player_Punter_Stats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_Player_Receiving_Stats> Game_Player_Receiving_Stats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_Player_Rushing_Stats> Game_Player_Rushing_Stats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hall_of_Fame> Hall_of_Fame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Injury> Injuries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player_Awards> Player_Awards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player_Ratings> Player_Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Training_Camp_by_Season> Training_Camp_by_Season { get; set; }
    }
}
