//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectatorFootball.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player_Awards
    {
        public long ID { get; set; }
        public long Year { get; set; }
        public long Player_ID { get; set; }
        public string Award { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
