//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectatorFootball.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player_Ratings
    {
        public long ID { get; set; }
        public long Player_ID { get; set; }
        public long Season_ID { get; set; }
        public long Ball_Safety_Rating { get; set; }
        public long Accuracy_Rating { get; set; }
        public long Decision_Making { get; set; }
        public long Arm_Strength_Rating { get; set; }
        public long Pass_Block_Rating { get; set; }
        public long Run_Block_Rating { get; set; }
        public long Running_Power_Rating { get; set; }
        public long Speed_Rating { get; set; }
        public long Agilty_Rating { get; set; }
        public long Hands_Rating { get; set; }
        public long Pass_Attack { get; set; }
        public long Run_Attack { get; set; }
        public long Tackle_Rating { get; set; }
        public long Kicker_Leg_Power { get; set; }
        public long Kicker_Leg_Accuracy { get; set; }
        public long Work_Ethic_Ratings { get; set; }
        public long Toughness_Ratings { get; set; }
        public Nullable<long> Sportsmanship_Ratings { get; set; }
    
        public virtual Season Season { get; set; }
    }
}
