//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectatorFootball.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playoff_Teams
    {
        public long Team_ID { get; set; }
        public long League_ID { get; set; }
        public long Rank { get; set; }
        public long Eliminated { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
