//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectatorFootball.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class settingsContext : DbContext
    {
        public settingsContext()
            : base("name=settingsContext")
        {
        }
        public settingsContext(string connString)
    : base(connString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Potential_First_Names> Potential_First_Names { get; set; }
        public virtual DbSet<Potential_Last_Names> Potential_Last_Names { get; set; }
        public virtual DbSet<Stock_Teams> Stock_Teams { get; set; }
    }
}
