//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectatorFootball.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Team()
        {
            this.Games = new HashSet<Game>();
            this.Games1 = new HashSet<Game>();
            this.Players = new HashSet<Player>();
            this.Playoff_Teams = new HashSet<Playoff_Teams>();
        }
    
        public long ID { get; set; }
        public long League_ID { get; set; }
        public string Owner { get; set; }
        public string City_Abr { get; set; }
        public string City { get; set; }
        public string Nickname { get; set; }
        public string Stadium_Name { get; set; }
        public string Stadium_Location { get; set; }
        public string Stadium_Capacity { get; set; }
        public string Stadium_Img_Path { get; set; }
        public string Helmet_img_path { get; set; }
        public string Helmet_Color { get; set; }
        public string Helmet_Logo_Color { get; set; }
        public string Helmet_Facemask_Color { get; set; }
        public string Socks_Color { get; set; }
        public string Cleats_Color { get; set; }
        public string Home_jersey_Color { get; set; }
        public string Home_Sleeve_Color { get; set; }
        public string Home_Jersey_Number_Color { get; set; }
        public string Home_Jersey_Number_Outline_Color { get; set; }
        public string Home_Jersey_Shoulder_Stripe { get; set; }
        public string Home_Jersey_Sleeve_Stripe_Color_1 { get; set; }
        public string Home_Jersey_Sleeve_Stripe_Color_2 { get; set; }
        public string Home_Jersey_Sleeve_Stripe_Color_3 { get; set; }
        public string Home_Jersey_Sleeve_Stripe_Color_4 { get; set; }
        public string Home_Jersey_Sleeve_Stripe_Color_5 { get; set; }
        public string Home_Jersey_Sleeve_Stripe_Color_6 { get; set; }
        public string Home_Pants_Color { get; set; }
        public string Home_Pants_Stripe_Color_1 { get; set; }
        public string Home_Pants_Stripe_Color_2 { get; set; }
        public string Home_Pants_Stripe_Color_3 { get; set; }
        public string Away_jersey_Color { get; set; }
        public string Away_Sleeve_Color { get; set; }
        public string Away_Jersey_Number_Color { get; set; }
        public string Away_Jersey_Number_Outline_Color { get; set; }
        public string Away_Jersey_Shoulder_Stripe { get; set; }
        public string Away_Jersey_Sleeve_Stripe_Color_1 { get; set; }
        public string Away_Jersey_Sleeve_Stripe_Color_2 { get; set; }
        public string Away_Jersey_Sleeve_Stripe_Color_3 { get; set; }
        public string Away_Jersey_Sleeve_Stripe_Color_4 { get; set; }
        public string Away_Jersey_Sleeve_Stripe_Color_5 { get; set; }
        public string Away_Jersey_Sleeve_Stripe_Color_6 { get; set; }
        public string Away_Pants_Color { get; set; }
        public string Away_Pants_Stripe_Color_1 { get; set; }
        public string Away_Pants_Stripe_Color_2 { get; set; }
        public string Away_Pants_Stripe_Color_3 { get; set; }
        public long Stadium_Field_Type { get; set; }
        public string Stadium_Field_Color { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game> Games { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game> Games1 { get; set; }
        public virtual League League { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player> Players { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Playoff_Teams> Playoff_Teams { get; set; }
    }
}
