//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectatorFootball.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teams_by_Season
    {
        public long ID { get; set; }
        public long Franchise_ID { get; set; }
        public long Team_Slot { get; set; }
        public long Season_ID { get; set; }
        public string Owner { get; set; }
        public string City_Abr { get; set; }
        public string City { get; set; }
        public string Nickname { get; set; }
        public string Stadium_Name { get; set; }
        public string Stadium_Location { get; set; }
        public string Stadium_Capacity { get; set; }
        public string Stadium_Img_Path { get; set; }
        public string Stadium_Image_File { get; set; }
        public string Helmet_img_path { get; set; }
        public string Helmet_Image_File { get; set; }
        public string Helmet_Color { get; set; }
        public string Helmet_Logo_Color { get; set; }
        public string Helmet_Facemask_Color { get; set; }
        public string Socks_Color { get; set; }
        public string Cleats_Color { get; set; }
        public string Home_jersey_Color { get; set; }
        public string Home_Sleeve_Color { get; set; }
        public string Home_Jersey_Number_Color { get; set; }
        public string Home_Jersey_Number_Outline_Color { get; set; }
        public string Home_Jersey_Shoulder_Stripe { get; set; }
        public string Home_Jersey_Sleeve_Stripe_Color_1 { get; set; }
        public string Home_Jersey_Sleeve_Stripe_Color_2 { get; set; }
        public string Home_Jersey_Sleeve_Stripe_Color_3 { get; set; }
        public string Home_Jersey_Sleeve_Stripe_Color_4 { get; set; }
        public string Home_Jersey_Sleeve_Stripe_Color_5 { get; set; }
        public string Home_Jersey_Sleeve_Stripe_Color_6 { get; set; }
        public string Home_Pants_Color { get; set; }
        public string Home_Pants_Stripe_Color_1 { get; set; }
        public string Home_Pants_Stripe_Color_2 { get; set; }
        public string Home_Pants_Stripe_Color_3 { get; set; }
        public string Away_jersey_Color { get; set; }
        public string Away_Sleeve_Color { get; set; }
        public string Away_Jersey_Number_Color { get; set; }
        public string Away_Jersey_Number_Outline_Color { get; set; }
        public string Away_Jersey_Shoulder_Stripe { get; set; }
        public string Away_Jersey_Sleeve_Stripe_Color_1 { get; set; }
        public string Away_Jersey_Sleeve_Stripe_Color_2 { get; set; }
        public string Away_Jersey_Sleeve_Stripe_Color_3 { get; set; }
        public string Away_Jersey_Sleeve_Stripe_Color_4 { get; set; }
        public string Away_Jersey_Sleeve_Stripe_Color_5 { get; set; }
        public string Away_Jersey_Sleeve_Stripe_Color_6 { get; set; }
        public string Away_Pants_Color { get; set; }
        public string Away_Pants_Stripe_Color_1 { get; set; }
        public string Away_Pants_Stripe_Color_2 { get; set; }
        public string Away_Pants_Stripe_Color_3 { get; set; }
        public long Stadium_Field_Type { get; set; }
        public string Stadium_Field_Color { get; set; }
    
        public virtual Franchise Franchise { get; set; }
        public virtual Season Season { get; set; }
    }
}
