using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SpectatorFootball.Enum
{
    public enum Graphics_Player_States
    {
        STANDING,
        RUNNING_1,
        RUNNING_2,
        RUNNING_3,
        RUNNING_4,
        FG_KICK,
        ABOUT_TO_CATCH_KICK,
        RUNNING_WITH_BALL_1,
        RUNNING_WITH_BALL_2,
        RUNNING_WITH_BALL_3,
        RUNNING_WITH_BALL_4,
        BLOCKING_1,
        BLOCKING_2,
        BLOCKING_3,
        RUNNING_UP_1,
        RUNNING_UP_2,
        RUNNING_UP_3,
        RUNNING_UP_4,
        RUNNING_DOWN_1,
        RUNNING_DOWN_2,
        RUNNING_DOWN_3,
        RUNNING_DOWN_4,
        RUNNING_UP_WITH_BALL_1,
        RUNNING_UP_WITH_BALL_2,
        RUNNING_UP_WITH_BALL_3,
        RUNNING_UP_WITH_BALL_4,
        RUNNING_DOWN_WITH_BALL_1,
        RUNNING_DOWN_WITH_BALL_2,
        RUNNING_DOWN_WITH_BALL_3,
        RUNNING_DOWN_WITH_BALL_4,
        TACKLING_1,
        TACKLING_2,
        TACKLING_3,
        TACKLED_1,
        TACKLED_2,
        TACKLED_3,
        ON_BACK,
        RUNNING_BACKWORDS_1,
        RUNNING_BACKWORDS_2,
        RUNNING_BACKWORDS_3,
        RUNNING_BACKWORDS_4,
        KNEELING_1,
        KNEELING_2,
        KNEELING_3,
        FALL_ON_BALL_1,
        FALL_ON_BALL_2,
        FALL_ON_BALL_3,
        PUNTER_READY,
        PUNTER_RUN_1,
        PUNTER_RUN_2,
        PUNTER_RUN_3,
        PUNTER_RUN_4,
        PUNTER_KICK_1,
        PUNTER_KICK_2,
        PUNTER_KICK_3,
        PUNTER_AFTER_KICK_1,
        PUNTER_AFTER_KICK_2,
        BLOCK_KICK,
        CROUCH_BLOCK_1,
        CROUCH_BLOCK_2,
        STANDING_WITH_BALL,
        FG_HOLDER_READY,
        FG_HOLDER_1,
        FG_HOLDER_2,
        FG_HOLDER_3
    }
}
